name: Xcode - Essential Feed

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-11

    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.0'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          xcodebuild build-for-testing -project EssentialFeed.xcodeproj -scheme CI CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
      - name: Test
        run: |
          xcodebuild test -project EssentialFeed.xcodeproj -scheme CI  CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty && exit ${PIPESTATUS[0]}
